GET http://localhost:4000/v1/healthcheck HTTP/1.1
Host: localhost:4000


####

GET http://localhost:4000/v1/movies/3 HTTP/1.1
Host: localhost:4000
Content-Type: application/json

### 

POST http://localhost:4000/v1/movies HTTP/1.1
Host: localhost:4000
Content-Type: application/json

{
    "title": "The Breakfast club",
    "year": 1986,
    "runtime": "96 mins",
    "genres": ["drama"]
}
###

PUT http://localhost:4000/v1/movies/4 HTTP/1.1
Host: localhost:4000
Content-Type: application/json

{
    "title": "The Breakfast club updated",
    "year": 1996,
    "runtime": "86 mins",
    "genres": ["drama", "action"]
}

###

DELETE http://localhost:4000/v1/movies/4 HTTP/1.1
Host: localhost:4000
Content-Type: application/json